### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by myfittinglife** [raghavk92/Kontroller#4]
It doesn't work on my phone, my android version is 10.

**Comment by raghavk92** [comment]
@myfittinglife what is the device you are using. The app works on pixel 3 so it should work on yours too unless your device manufacturer has disabled this feature.

If it is disabled you are not alone. All one plus phones are disabled and many others too. 

You can check if you device supports this BluetoothHID device profile . If it doesnt then ask your device manufacturer to fix it . Scold/Abuse them if you can. 

You can check if this feature is enabled or not by using this app i made for this very purpose
https://play.google.com/store/apps/details?id=com.rkaneapplabs.bluetooth_hid.bluetoothproxy

**Comment by myfittinglife** [comment]
My phone is Mi9. My device supports the BluetoothHID device profile and this software works. https://play.google.com/store/apps/details?id=io.appground.blek

**Comment by raghavk92** [comment]
So if you have other apps installed at the same time using this feature. You would need to reset your bluetooth connection with the Host device with which you are using the bluetooth HID device profile.

To use the app
- Remove all previous bluetooth connections with the host device from the android settings menu. The Bluetooth HID protocol is set by the blek app in your case so wont work with Kontroller.
- Open the app
- Generate bluetooth connection from the host device to the phone(acting as a mouse/keyboard) where the kontroller app is open
- Accept the request on your phone without leaving the app screen
- Then hopefully kontroller should work

If it still doesnt work then let me know . I ll have to recheck what the issue is .

**Comment by myfittinglife** [comment]
Thank you for your reply. I tried it just now and found that the program works when only one paired Bluetooth device is saved in the Bluetooth settings of the phone. Maybe you can click the list of paired phones and then establish a connection, otherwise you need to delete all the paired phones when you change the device, which is very bad

**Comment by raghavk92** [comment]
I dont think you need to remove all previous connections with all the devices in your bluetooth android settings. You just need to remove the old bluetooth settings with the host device ( with which you want a bluetooth HID connection)
